language: python
python: 3.5
sudo: false

branches:
    only:
        - crawler-integration
        - /^\d\.\d+$/

install:
    - pip install -U tox codecov

script: tox

after_success:
    - codecov

cache:
    directories:
        - $HOME/.cache/pip

