language: python
python: 3.5
sudo: false

branches:
    only:
        - master
        - /^\d\.\d+$/

install:
    - pip install -U tox codecov
    - pip install proxy.py
    - proxy.py --port 8123 &

script: tox

after_success:
    - codecov

cache:
    directories:
        - $HOME/.cache/pip

